=== Icikowski/vanitygen/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "vanitygen configuration file",
    "properties": {
        "domain": {
            "type": "string",
            "description": "Domain name (without http[s])"
        },
        "siteName": {
            "type": "string",
            "description": "Package site's name"
        },
        "author": {
            "type": "string",
            "description": "Package site's author name"
        },
        "docs": {
            "type": "string",
            "description": "Docs server URL",
            "format": "uri",
            "default": "https://pkg.go.dev"
        },
        "pkgs": {
            "type": "array",
            "description": "List of packages",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "description": "Package definition",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Package name"
                    },
                    "provider": {
                        "type": "string",
                        "description": "Repository provider",
                        "enum": [
                            "gitea",
                            "github",
                            "gitlab",
                            "sourcehut"
                        ]
                    },
                    "repoUrl": {
                        "type": "string",
                        "description": "Package repository URL",
                        "format": "uri"
                    },
                    "branch": {
                        "type": "string",
                        "description": "Default branch name of package repository"
                    },
                    "website": {
                        "type": "string",
                        "description": "Package website",
                        "format": "uri"
                    },
                    "subpackages": {
                        "type": "array",
                        "description": "Subpackages of package (optional)",
                        "items": {
                            "type": "string",
                            "description": "Subpackage name"
                        },
                        "uniqueItems": true,
                        "default": null
                    }
                },
                "required": [
                    "name",
                    "provider",
                    "repoUrl",
                    "branch"
                ]
            }
        }
    },
    "required": [
        "domain",
        "siteName",
        "author",
        "pkgs"
    ]
}

=== Icikowski/vanitygen/examples/vanitygen.json
{
    "$schema": "https://raw.githubusercontent.com/Icikowski/vanitygen/main/config.schema.json",
    "domain": "pkg.somesite.com",
    "siteName": "Go packages",
    "author": "John Doe",
    "docs": "https://pkg.go.dev",
    "pkgs": [
      {
        "name": "utils",
        "provider": "github",
        "repoUrl": "https://github.com/someuser/someutils",
        "branch": "main"
      },
      {
        "name": "tools",
        "provider": "gitlab",
        "repoUrl": "https://gitlab.com/someuser/sometools",
        "branch": "devel"
      },
      {
        "name": "awesome",
        "provider": "gitea",
        "repoUrl": "https://try.gitea.io/someuser/some-awesome-package",
        "branch": "staging",
        "website": "https://somesite.com/my-awesome-package"
      },
      {
        "name": "others",
        "provider": "sourcehut",
        "repoUrl": "https://git.sr.ht/~someuser/someotherpackage",
        "branch": "master"
      }
    ]
  }
